In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\isaac\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\isaac\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\isaac\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\isaac\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\isaac\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\isaac\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [9]:
file_path = r'C:\Users\isaac\OneDrive\Desktop\Project_Capstone 2\Project_Capstone_2\dataset\rawdata\Sales Dataset - Sales Dataset.csv'

In [10]:
df = pd.read_csv(file_path)

In [49]:
df.head()

,Order_ID,Amount,Profit,Quantity,Category,Sub-Category,Payment_Mode,Order_Date,State,City,Year-Month,Customer_Name
0,1,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla
1,2,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan
2,3,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,New York,Buffalo,2021-07,Robert Stone
3,4,4975,1330,14,Electronics,Printers,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla
4,5,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan

In [78]:
df.columns = df.columns.str.replace(" ", "_").str.strip()
df.columns = df.columns.str.replace("PaymentMode", "Payment_Mode").str.strip()
df.columns = df.columns.str.replace("CustomerName", "Customer_Name").str.strip()
df.columns = df.columns.str.replace("Year-Month", "Year_Month").str.strip()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1194 entries, 0 to 1193
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1194 non-null   object
 1   Amount         1194 non-null   int64
 2   Profit         1194 non-null   int64
 3   Quantity       1194 non-null   int64
 4   Category       1194 non-null   object
 5   Sub-Category   1194 non-null   object
 6   Payment_Mode   1194 non-null   object
 7   Order_Date     1194 non-null   datetime64[ns]
 8   State          1194 non-null   object
 9   City           1194 non-null   object
 10  Year_Month     1194 non-null   period[M]
 11  Customer_Name  1194 non-null   object
 12  Customer_ID    1194 non-null   object
 13  Product_ID     1194 non-null   object
 14  Location_ID    1194 non-null   object
 15  Date_ID        1194 non-null   object
dtypes: datetime64[ns](1), int64(3), object(11), period[M](1)
memory usage: 149.4+ KB

In [79]:
df.head()

,Order_ID,Amount,Profit,Quantity,Category,Sub-Category,Payment_Mode,Order_Date,State,City,Year_Month,Customer_Name,Customer_ID,Product_ID,Location_ID,Date_ID
0,OID-10001,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla,CID-10001,PID-10001,LID-10001,DID-10001
1,OID-10002,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan,CID-10002,PID-10002,LID-10002,DID-10002
2,OID-10003,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,New York,Buffalo,2021-07,Robert Stone,CID-10003,PID-10003,LID-10003,DID-10003
3,OID-10004,4975,1330,14,Electronics,Printers,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla,CID-10004,PID-10004,LID-10004,DID-10004
4,OID-10005,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan,CID-10005,PID-10005,LID-10005,DID-10005

In [81]:
# convert Order_Date to datetime\n"

df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df["Year-Month"] = df["Order_Date"].dt.to_period("M")

In [82]:
df.head()

,Order_ID,Amount,Profit,Quantity,Category,Sub-Category,Payment_Mode,Order_Date,State,City,Year_Month,Customer_Name,Customer_ID,Product_ID,Location_ID,Date_ID,Year-Month
0,OID-10001,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla,CID-10001,PID-10001,LID-10001,DID-10001,2023-06
1,OID-10002,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan,CID-10002,PID-10002,LID-10002,DID-10002,2024-12
2,OID-10003,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,New York,Buffalo,2021-07,Robert Stone,CID-10003,PID-10003,LID-10003,DID-10003,2021-07
3,OID-10004,4975,1330,14,Electronics,Printers,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla,CID-10004,PID-10004,LID-10004,DID-10004,2023-06
4,OID-10005,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan,CID-10005,PID-10005,LID-10005,DID-10005,2024-12

In [65]:
#Reset to avoid not being continous
df = df.reset_index(drop=True)
df["Order_ID"] = "OID-" + (10001 + df.index).astype(str)

In [66]:
df.head()

,Order_ID,Amount,Profit,Quantity,Category,Sub-Category,Payment_Mode,Order_Date,State,City,Year-Month,Customer_Name
0,OID-10001,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla
1,OID-10002,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan
2,OID-10003,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,New York,Buffalo,2021-07,Robert Stone
3,OID-10004,4975,1330,14,Electronics,Printers,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla
4,OID-10005,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan

In [73]:
# Create new CustomerID column
df["Customer_ID"] = range(1001, 1001 + len(df))
df["Product_ID"] = range(1001, 1001 + len(df))

# Preview
df.head()

,Order_ID,Amount,Profit,Quantity,Category,Sub-Category,Payment_Mode,Order_Date,State,City,Year-Month,Customer_Name,Customer_ID,Product_ID
0,OID-10001,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla,1001,1001
1,OID-10002,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan,1002,1002
2,OID-10003,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,New York,Buffalo,2021-07,Robert Stone,1003,1003
3,OID-10004,4975,1330,14,Electronics,Printers,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla,1004,1004
4,OID-10005,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan,1005,1005

In [76]:
df = df.reset_index(drop=True)
df["Customer_ID"] = "CID-" + (10001 + df.index).astype(str)
df["Product_ID"] = "PID-" + (10001 + df.index).astype(str)
df["Location_ID"] = "LID-" + (10001 + df.index).astype(str)
df["Date_ID"] = "DID-" + (10001 + df.index).astype(str)
df.head()

,Order_ID,Amount,Profit,Quantity,Category,Sub-Category,Payment_Mode,Order_Date,State,City,Year-Month,Customer_Name,Customer_ID,Product_ID,Location_ID,Date_ID
0,OID-10001,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla,CID-10001,PID-10001,LID-10001,DID-10001
1,OID-10002,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan,CID-10002,PID-10002,LID-10002,DID-10002
2,OID-10003,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,New York,Buffalo,2021-07,Robert Stone,CID-10003,PID-10003,LID-10003,DID-10003
3,OID-10004,4975,1330,14,Electronics,Printers,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla,CID-10004,PID-10004,LID-10004,DID-10004
4,OID-10005,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan,CID-10005,PID-10005,LID-10005,DID-10005

In [77]:
df.tail()

,Order_ID,Amount,Profit,Quantity,Category,Sub-Category,Payment_Mode,Order_Date,State,City,Year-Month,Customer_Name,Customer_ID,Product_ID,Location_ID,Date_ID
1189,OID-11190,8825,3594,15,Furniture,Tables,Debit Card,2024-07-31,New York,New York City,2024-07,Megan Mclean,CID-11190,PID-11190,LID-11190,DID-11190
1190,OID-11191,2082,642,8,Electronics,Phones,EMI,2020-06-02,New York,Rochester,2020-06,Caitlin Hunt,CID-11191,PID-11191,LID-11191,DID-11191
1191,OID-11192,2082,642,8,Electronics,Phones,EMI,2022-12-15,Texas,Austin,2022-12,Jenna Holland,CID-11192,PID-11192,LID-11192,DID-11192
1192,OID-11193,2082,642,8,Electronics,Phones,EMI,2020-08-07,New York,Buffalo,2020-08,Stephanie Oconnell,CID-11193,PID-11193,LID-11193,DID-11193
1193,OID-11194,914,163,13,Office Supplies,Markers,UPI,2024-10-26,Illinois,Chicago,2024-10,Andrea Hill,CID-11194,PID-11194,LID-11194,DID-11194

In [84]:
# Derive year, month, quarter, date_id for dim_date
df["Year"]    = df["Order_Date"].dt.year
df["Month"]   = df["Order_Date"].dt.month
df["Quarter"] = df["Order_Date"].dt.quarter

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1194 entries, 0 to 1193
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1194 non-null   object
 1   Amount         1194 non-null   int64
 2   Profit         1194 non-null   int64
 3   Quantity       1194 non-null   int64
 4   Category       1194 non-null   object
 5   Sub-Category   1194 non-null   object
 6   Payment_Mode   1194 non-null   object
 7   Order_Date     1194 non-null   datetime64[ns]
 8   State          1194 non-null   object
 9   City           1194 non-null   object
 10  Year_Month     1194 non-null   period[M]
 11  Customer_Name  1194 non-null   object
 12  Customer_ID    1194 non-null   object
 13  Product_ID     1194 non-null   object
 14  Location_ID    1194 non-null   object
 15  Date_ID        1194 non-null   object
 16  Year-Month     1194 non-null   period[M]
 17  Year           1194 non-null   int32
 18  Month          1194 non-null   int32
 19  Quarter        1194 non-null   int32
dtypes: datetime64[ns](1), int32(3), int64(3), object(11), period[M](2)
memory usage: 172.7+ KB

In [86]:
df.head()

,Order_ID,Amount,Profit,Quantity,Category,Sub-Category,Payment_Mode,Order_Date,State,City,Year_Month,Customer_Name,Customer_ID,Product_ID,Location_ID,Date_ID,Year-Month,Year,Month,Quarter
0,OID-10001,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla,CID-10001,PID-10001,LID-10001,DID-10001,2023-06,2023,6,2
1,OID-10002,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan,CID-10002,PID-10002,LID-10002,DID-10002,2024-12,2024,12,4
2,OID-10003,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,New York,Buffalo,2021-07,Robert Stone,CID-10003,PID-10003,LID-10003,DID-10003,2021-07,2021,7,3
3,OID-10004,4975,1330,14,Electronics,Printers,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla,CID-10004,PID-10004,LID-10004,DID-10004,2023-06,2023,6,2
4,OID-10005,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan,CID-10005,PID-10005,LID-10005,DID-10005,2024-12,2024,12,4

In [87]:
# Drop duplicates & nulls
df.drop_duplicates(inplace=True)
df.dropna(inplace=True)

In [89]:
# ── 3. TRANSFORMATIONS ────────────────────────────────────────────────────────

# Monthly profit aggregation
monthly_profit = (
    df.groupby('Year_Month')['Profit']
    .sum()
    .reset_index()
    .rename(columns={'Profit': 'Total_Profit'})
    .sort_values('Year_Month')
)

# Top 10 customers by total amount
top_customers = (
    df.groupby('Customer_Name')['Amount']
    .sum()
    .reset_index()
    .rename(columns={'Amount': 'Total_Amount'})
    .sort_values('Total_Amount', ascending=False)
    .head(10)
)

# Quantity sold per category
qty_per_category = (
    df.groupby('Category')['Quantity']
    .sum()
    .reset_index()
    .rename(columns={'Quantity': 'Total_Quantity'})
    .sort_values('Total_Quantity', ascending=False)
)

# Cities with low profitability (below median profit)
city_profit = (
    df.groupby('City')['Profit']
    .sum()
    .reset_index()
    .rename(columns={'Profit': 'Total_Profit'})
)
median_profit = city_profit['Total_Profit'].median()
low_profit_cities = city_profit[city_profit['Total_Profit'] < median_profit].sort_values('Total_Profit')

# ── 4. WRITE TO CSV ───────────────────────────────────────────────────────────
df.to_csv('Cleaned_Sales.csv', index=False)
monthly_profit.to_csv('Monthly_Profit.csv', index=False)
top_customers.to_csv('Top_Customers.csv', index=False)
qty_per_category.to_csv('Qty_Per_Category.csv', index=False)
low_profit_cities.to_csv('Low_Profit_Cities.csv', index=False)

print("Done. Files written:")
print("  Cleaned_Sales.csv, Monthly_Profit.csv, Top_Customers.csv, Qty_Per_Category.csv, Low_Profit_Cities.csv")

Done. Files written:
  Cleaned_Sales.csv, Monthly_Profit.csv, Top_Customers.csv, Qty_Per_Category.csv, Low_Profit_Cities.csv

In [90]:
cleaned_sales    = pd.read_csv('cleaned_sales.csv')
monthly_profit   = pd.read_csv('monthly_profit.csv')
top_customers    = pd.read_csv('top_customers.csv')
qty_per_category = pd.read_csv('qty_per_category.csv')
low_profit_cities = pd.read_csv('low_profit_cities.csv')

print("=== Cleaned Sales ===")
print(cleaned_sales.head())

print("\n=== Monthly Profit ===")
print(monthly_profit)

print("\n=== Top Customers ===")
print(top_customers)

print("\n=== Quantity per Category ===")
print(qty_per_category)

print("\n=== Low Profit Cities ===")
print(low_profit_cities)

=== Cleaned Sales ===
    Order_ID  Amount  Profit  Quantity     Category      Sub-Category  \
0  OID-10001    9726    1275         5  Electronics  Electronic Games
1  OID-10002    9726    1275         5  Electronics  Electronic Games
2  OID-10003    9726    1275         5  Electronics  Electronic Games
3  OID-10004    4975    1330        14  Electronics          Printers
4  OID-10005    4975    1330        14  Electronics          Printers

  Payment_Mode  Order_Date     State     City Year_Month  Customer_Name  \
0          UPI  2023-06-27   Florida    Miami    2023-06  David Padilla
1          UPI  2024-12-27  Illinois  Chicago    2024-12  Connor Morgan
2          UPI  2021-07-25  New York  Buffalo    2021-07   Robert Stone
3          UPI  2023-06-27   Florida    Miami    2023-06  David Padilla
4          UPI  2024-12-27  Illinois  Chicago    2024-12  Connor Morgan

  Customer_ID Product_ID Location_ID    Date_ID Year-Month  Year  Month  \
0   CID-10001  PID-10001   LID-10001  DID-10001    2023-06  2023      6
1   CID-10002  PID-10002   LID-10002  DID-10002    2024-12  2024     12
2   CID-10003  PID-10003   LID-10003  DID-10003    2021-07  2021      7
3   CID-10004  PID-10004   LID-10004  DID-10004    2023-06  2023      6
4   CID-10005  PID-10005   LID-10005  DID-10005    2024-12  2024     12

   Quarter
0        2
1        4
2        3
3        2
4        4

=== Monthly Profit ===
   Year_Month  Total_Profit
0     2020-03          6192
1     2020-04         36156
2     2020-05         24294
3     2020-06          9489
4     2020-07         12008
..        ...           ...
56    2024-11         15657
57    2024-12         20981
58    2025-01         38595
59    2025-02         28151
60    2025-03         13497

[61 rows x 2 columns]

=== Top Customers ===
        Customer_Name  Total_Amount
0          Cory Evans         28557
1       Emily Ellison         27352
2       George Foster         27352
3   Nicholas Anderson         27352
4  Katherine Williams         25121
5   Jacqueline Harris         24433
6       Randy Johnson         24295
7          Tammy Bell         23895
8         Brian Green         23737
9       Zachary Perez         23737

=== Quantity per Category ===
          Category  Total_Quantity
0        Furniture            4441
1      Electronics            4258
2  Office Supplies            4046

=== Low Profit Cities ===
          City  Total_Profit
0     Columbus         56277
1  Los Angeles         69264
2        Tampa         70842
3      Houston         72659
4       Peoria         76106
5   Cincinnati         78788
6      Chicago         80061
7    Cleveland         81454
8       Austin         82638