In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\isaac\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\isaac\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\isaac\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\isaac\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\isaac\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\isaac\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [9]:
file_path = r'C:\Users\isaac\OneDrive\Desktop\Project_Capstone 2\Project_Capstone_2\dataset\rawdata\Sales Dataset - Sales Dataset.csv'

In [10]:
df = pd.read_csv(file_path)

In [49]:
df.head()

,Order_ID,Amount,Profit,Quantity,Category,Sub-Category,Payment_Mode,Order_Date,State,City,Year-Month,Customer_Name
0,1,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla
1,2,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan
2,3,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,New York,Buffalo,2021-07,Robert Stone
3,4,4975,1330,14,Electronics,Printers,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla
4,5,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan

In [50]:
df.columns = df.columns.str.replace(" ", "_").str.strip()
df.columns = df.columns.str.replace("PaymentMode", "Payment_Mode").str.strip()
df.columns = df.columns.str.replace("CustomerName", "Customer_Name").str.strip()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1194 entries, 0 to 1193
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1194 non-null   int64
 1   Amount         1194 non-null   int64
 2   Profit         1194 non-null   int64
 3   Quantity       1194 non-null   int64
 4   Category       1194 non-null   object
 5   Sub-Category   1194 non-null   object
 6   Payment_Mode   1194 non-null   object
 7   Order_Date     1194 non-null   datetime64[ns]
 8   State          1194 non-null   object
 9   City           1194 non-null   object
 10  Year-Month     1194 non-null   period[M]
 11  Customer_Name  1194 non-null   object
dtypes: datetime64[ns](1), int64(4), object(6), period[M](1)
memory usage: 112.1+ KB

In [51]:
df.head()

,Order_ID,Amount,Profit,Quantity,Category,Sub-Category,Payment_Mode,Order_Date,State,City,Year-Month,Customer_Name
0,1,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla
1,2,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan
2,3,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,New York,Buffalo,2021-07,Robert Stone
3,4,4975,1330,14,Electronics,Printers,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla
4,5,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan

In [28]:
df = df.drop(columns=['Order_Key', 'Clean_Order_ID'])

In [29]:
df.head()

,Order_ID,Amount,Profit,Quantity,Category,Sub-Category,Payment_Mode,Order_Date,Customer_Name,State,City,Year-Month
0,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,David Padilla,Florida,Miami,2023-06
1,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Connor Morgan,Illinois,Chicago,2024-12
2,B-26776,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,Robert Stone,New York,Buffalo,2021-07
3,B-26776,4975,1330,14,Electronics,Printers,UPI,2023-06-27,David Padilla,Florida,Miami,2023-06
4,B-26776,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Connor Morgan,Illinois,Chicago,2024-12

In [52]:
# convert Order_Date to datetime\n"

df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df["Year-Month"] = df["Order_Date"].dt.to_period("M")

In [53]:
df.head()

,Order_ID,Amount,Profit,Quantity,Category,Sub-Category,Payment_Mode,Order_Date,State,City,Year-Month,Customer_Name
0,1,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla
1,2,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan
2,3,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,New York,Buffalo,2021-07,Robert Stone
3,4,4975,1330,14,Electronics,Printers,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla
4,5,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan

In [65]:
#Reset to avoid not being continous
df = df.reset_index(drop=True)
df["Order_ID"] = "OID-" + (10001 + df.index).astype(str)

In [66]:
df.head()

,Order_ID,Amount,Profit,Quantity,Category,Sub-Category,Payment_Mode,Order_Date,State,City,Year-Month,Customer_Name
0,OID-10001,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla
1,OID-10002,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan
2,OID-10003,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,New York,Buffalo,2021-07,Robert Stone
3,OID-10004,4975,1330,14,Electronics,Printers,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla
4,OID-10005,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan

In [73]:
# Create new CustomerID column
df["Customer_ID"] = range(1001, 1001 + len(df))
df["Product_ID"] = range(1001, 1001 + len(df))

# Preview
df.head()

,Order_ID,Amount,Profit,Quantity,Category,Sub-Category,Payment_Mode,Order_Date,State,City,Year-Month,Customer_Name,Customer_ID,Product_ID
0,OID-10001,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla,1001,1001
1,OID-10002,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan,1002,1002
2,OID-10003,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,New York,Buffalo,2021-07,Robert Stone,1003,1003
3,OID-10004,4975,1330,14,Electronics,Printers,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla,1004,1004
4,OID-10005,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan,1005,1005

In [74]:
df = df.reset_index(drop=True)
df["Customer_ID"] = "CID-" + (10001 + df.index).astype(str)
df["Product_ID"] = "PID-" + (10001 + df.index).astype(str)
df.head()

,Order_ID,Amount,Profit,Quantity,Category,Sub-Category,Payment_Mode,Order_Date,State,City,Year-Month,Customer_Name,Customer_ID,Product_ID
0,OID-10001,9726,1275,5,Electronics,Electronic Games,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla,CID-10001,PID-10001
1,OID-10002,9726,1275,5,Electronics,Electronic Games,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan,CID-10002,PID-10002
2,OID-10003,9726,1275,5,Electronics,Electronic Games,UPI,2021-07-25,New York,Buffalo,2021-07,Robert Stone,CID-10003,PID-10003
3,OID-10004,4975,1330,14,Electronics,Printers,UPI,2023-06-27,Florida,Miami,2023-06,David Padilla,CID-10004,PID-10004
4,OID-10005,4975,1330,14,Electronics,Printers,UPI,2024-12-27,Illinois,Chicago,2024-12,Connor Morgan,CID-10005,PID-10005

In [75]:
df.tail()

,Order_ID,Amount,Profit,Quantity,Category,Sub-Category,Payment_Mode,Order_Date,State,City,Year-Month,Customer_Name,Customer_ID,Product_ID
1189,OID-11190,8825,3594,15,Furniture,Tables,Debit Card,2024-07-31,New York,New York City,2024-07,Megan Mclean,CID-11190,PID-11190
1190,OID-11191,2082,642,8,Electronics,Phones,EMI,2020-06-02,New York,Rochester,2020-06,Caitlin Hunt,CID-11191,PID-11191
1191,OID-11192,2082,642,8,Electronics,Phones,EMI,2022-12-15,Texas,Austin,2022-12,Jenna Holland,CID-11192,PID-11192
1192,OID-11193,2082,642,8,Electronics,Phones,EMI,2020-08-07,New York,Buffalo,2020-08,Stephanie Oconnell,CID-11193,PID-11193
1193,OID-11194,914,163,13,Office Supplies,Markers,UPI,2024-10-26,Illinois,Chicago,2024-10,Andrea Hill,CID-11194,PID-11194